### ISSUE TITLE
GithubLanguage is of type string not uint

### ISSUE THREAD

**Issue by Metnew** [shuheiktgw/go-travis#12]
Docs - https://developer.travis-ci.com/resource/repository#Repository

Expected: string
Actual: uint

**Comment by Metnew** [comment]
PR: https://github.com/shuheiktgw/go-travis/pull/13

**Comment by shuheiktgw** [comment]
@Metnew Thanks for your PR! 👍 
I just merged it and released v0.1.9, so please use that!
