### ISSUE TITLE
Check Travis CI API v3 updates

### ISSUE THREAD

**Issue by shuheiktgw** [shuheiktgw/go-travis#18]
I need to check if there are any updates on the API I have not noticed yet. I'm pretty sure there are some.

**Comment by jsdidierlaurent** [comment]
I do not know if it's new, but it will be great if we could get the standard version of a commit.
I need to get the author from a build : https://developer.travis-ci.com/resource/commit#Commit

**Comment by shuheiktgw** [comment]
@jsdidierlaurent Thanks for your information! It seems they've added `committer` and `author` props to `Commit`. Would you like to make a PR or I'll work on this when I have time! 👍

**Comment by shuheiktgw** [comment]
Now I've compared the API and the source code and listed up all the changes we need to make! 

https://github.com/shuheiktgw/go-travis/issues/19

I will close this issue but please feel free to work on the problem on Commit struct if you want! 👍

**Comment by shuheiktgw** [comment]
Ok, now I understand the problem correctly. Since we do not support eager loading, the objects associated with the resource always is in minimal representation. Usually, it's ok, but in this case, commit does not have its endpoint and there are no ways to get  commits in standard representation...
