### ISSUE TITLE
Access "config" attribute of a job

### ISSUE THREAD

**Issue by nbedos** [shuheiktgw/go-travis#65]
Is it possible to access the "config" attribute of a job?

"config" is listed on this page as one of the attributes of "job": https://developer.travis-ci.com/resource/jobs
It seems support was added for it a while back via https://github.com/shuheiktgw/go-travis/commit/81f36c5bc2f9c0441bfb66ab10e728e01fd53050#diff-b91d5620c6bf557e598604750ebe0062 but it seems to have been dropped.

For example when running the following query each job of the response includes a config attribute as shown below
```sh
$ curl -H "Travis-API-Version: 3" \
-H "User-Agent: API Explorer" \
-H "Authorization: token <token>" \
'https://api.travis-ci.org/builds?limit=1&include=build.jobs%2Cjob.config'
```

```json
"config": {
	"os": "linux",
	"dist": "xenial",
	"sudo": true,
	"group": "stable",
	"stage": "Test",
	"python": "3.8-dev",
	"script": [
		"make tests"
	],
	".result": "configured",
	"install": [
		"make install"
	],
	"language": "python",
	"global_env": "GITHUB_TOKEN=[secure]",
	"notifications": {
	        "email": false
        }
}
```

Thanks!

**Comment by shuheiktgw** [comment]
Thanks for reporting the issue! 😄 
I'll work on this when I have time, but if someone else want to take it, please feel free to do so.

**Comment by nbedos** [comment]
Thanks!
